# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - mwozad4dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    test-app-with-gradle:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
               
                with:
                    gradle-version: '8.2'
                    arguments: build
            -   name: jar jar 
                run: rm -rf build/libs/*-plain.jar

            -   name: Upload artifact for deployment job
                uses: actions/upload-artifact@v3
                with:
                    name: Zad4
                    path: '${{ github.workspace }}/build/libs/*.jar'
      
    deploy:
          runs-on: ubuntu-latest
          needs: test-app-with-gradle
          environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
            
          steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                name: Zad4
            
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                   app-name: 'mwozad4dev'
                   slot-name: 'Production'
                   package: '*.jar'
                   publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F70E76D33FBD496ABFFFC1F5E20A2FDC }}
